### ISSUE TITLE
Move the repo into kalliope project?

### ISSUE THREAD

**Issue by Sispheor** [FoxKyong/kalliope_starter_cs#1]
Can I propose you to open a repo in kalliope project for this starter kit?

**Comment by FoxKyong** [comment]
Ok, that would be possible. Can you give me a hint how to do that? I just check kalliope-repository and I didn't find how to create a repo there. I have never created repo in another projects.

**Comment by Sispheor** [comment]
It's because I need to create the project and give you the write access. It's done.
You can push the project [here](https://github.com/kalliope-project/kalliope_starter_cs).

I'll update it soon to add v0.4.6 support.

**Comment by FoxKyong** [comment]
Thanks, it's there. Should I continue keeping it up-to-date only there or also here?

**Comment by Sispheor** [comment]
No, you can remove the repo in your personal Github now.
I leave you a full access on the repo in kalliope project. Welcome into the team ! ;)
